model_list:
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: vertex_ai/claude-sonnet-4-6
      vertex_location: "global"
      vertex_project: "YOUR_PROJECT_ID"
      use_in_pass_through: true
  - model_name: claude-opus-4-6
    litellm_params:
      model: vertex_ai/claude-opus-4-6
      vertex_location: "global"
      vertex_project: "YOUR_PROJECT_ID"
      use_in_pass_through: true

  - model_name: claude-haiku-4-5
    litellm_params:
      model: vertex_ai/claude-haiku-4-5
      vertex_location: "global"
      vertex_project: "YOUR_PROJECT_ID"
      use_in_pass_through: true

litellm_settings:
  set_verbose: True
  callbacks:
    - strip_unsupported_params.strip_unsupported_params

router_settings:
  routing_strategy: "latency-based-routing"

general_settings:
  allow_user_auth: True
  proxy_batch_write_at: 1
  store_model_in_db: true
  store_prompts_in_spend_logs: true
